[package]
name = "rc-cli"
version = "0.1.0"
authors = ["Radoslaw Kumorek <radoslaw.kumorekit@gmail.com"]
edition = "2021"

[dependencies]
anyhow = "*"
rc-lib = { path = "../rc-lib"}
clap = { version = "4", features = [ "derive" ] }
log = "*"