[package]
name = "rc-lib"
version = "0.1.0"
authors = ["Radoslaw Kumorek <radoslaw.kumorekit@gmail.com"]
edition = "2021"

[dependencies]
log = "*"
pest = "2.6"
pest_derive = "2.6"
smart-default = "0.7.1"
snafu = "0.8.5"